# Generated by Django 4.2.30 on 2026-07-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, help_text='Why are you interested in this internship?', verbose_name='cover letter')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='resume')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('offer', 'Offer Extended'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20, verbose_name='status')),
                ('company_notes', models.TextField(blank=True, help_text='Internal notes from the recruitment team', verbose_name='company notes')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('ai_match_score', models.PositiveIntegerField(blank=True, help_text='AI-calculated compatibility score (0-100)', null=True, verbose_name='AI match score')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='applied at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.internship', verbose_name='internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'internship')},
            },
        ),
    ]
