# Generated by Django 4.2.30 on 2026-09-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_supervisor'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='accounts.supervisorprofile', verbose_name='assigned supervisor'),
        ),
        migrations.AddField(
            model_name='application',
            name='supervisor_email',
            field=models.EmailField(blank=True, help_text='Academic supervisor email provided during application', max_length=254, verbose_name='supervisor email'),
        ),
    ]
