# Generated by Django 4.2.30 on 2026-09-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_assigned_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed analytical scoring breakdown and CV formatting review', verbose_name='AI match breakdown'),
        ),
    ]
