# Generated by Django 4.2.30 on 2026-09-02 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(help_text='Internal code: pro, ultimate, student_pro, student_boost, basic', max_length=50, verbose_name='plan identifier')),
                ('plan_display_name', models.CharField(help_text='User facing title: Pro Recruiter, Student Career Boost, etc.', max_length=100, verbose_name='plan display title')),
                ('plan_category', models.CharField(choices=[('company', 'Company Recruitment Plan'), ('student', 'Student Career Plan')], default='company', max_length=20, verbose_name='plan category')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly Billing'), ('annual', 'Annual Billing')], default='monthly', max_length=20, verbose_name='billing cycle')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='subscription price')),
                ('currency', models.CharField(default='BDT', max_length=10, verbose_name='currency')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date')),
                ('expires_at', models.DateTimeField(verbose_name='expiry date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('warning_notified', models.BooleanField(default=False, help_text='True if the 7-day expiration reminder notification has already been triggered', verbose_name='7-day warning sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Unique identifier e.g. TXN-BKASH-894120', max_length=64, unique=True, verbose_name='transaction ID')),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash Mobile Banking'), ('nagad', 'Nagad Mobile Banking'), ('upay', 'Upay Mobile Banking'), ('card', 'Credit / Debit Card')], max_length=20, verbose_name='payment method')),
                ('account_number', models.CharField(blank=True, help_text='Masked account or card digits e.g. 017****9201 or **** 4242', max_length=50, verbose_name='account / card number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount paid')),
                ('currency', models.CharField(default='BDT', max_length=10, verbose_name='currency')),
                ('status', models.CharField(choices=[('completed', 'Completed & Verified'), ('pending', 'Pending Verification'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='transaction timestamp')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.subscription', verbose_name='associated subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='payer')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
