# Generated by Django 4.2.30 on 2026-07-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon class')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Internship Category',
                'verbose_name_plural': 'Internship Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(help_text='Detailed description of the internship role and responsibilities', verbose_name='description')),
                ('requirements', models.TextField(help_text='Skills and qualifications required for this position', verbose_name='requirements')),
                ('skills_required', models.TextField(blank=True, help_text='Comma-separated list of required skills', verbose_name='required skills')),
                ('internship_type', models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=20, verbose_name='type')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('duration', models.CharField(help_text='e.g., 3 months, 6 months', max_length=100, verbose_name='duration')),
                ('stipend', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly stipend amount in BDT', max_digits=10, null=True, verbose_name='monthly stipend')),
                ('positions', models.PositiveIntegerField(default=1, verbose_name='positions available')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('deadline', models.DateField(help_text='Last date to submit applications', verbose_name='application deadline')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internships', to='internships.internshipcategory', verbose_name='category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='accounts.companyprofile', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Internship',
                'verbose_name_plural': 'Internships',
                'ordering': ['-created_at'],
            },
        ),
    ]
