# Generated by Django 4.2.30 on 2026-08-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_subscription_plan'),
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='saved at')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_students', to='internships.internship', verbose_name='internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_internships', to='accounts.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Saved Internship',
                'verbose_name_plural': 'Saved Internships',
                'ordering': ['-saved_at'],
                'unique_together': {('student', 'internship')},
            },
        ),
    ]
