# Generated by Django 4.2.30 on 2026-09-02 09:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_savedinternship'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='positions',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='positions available'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='stipend',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly stipend amount in BDT', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='monthly stipend'),
        ),
    ]
