# Generated by Django 4.2.30 on 2026-07-16 10:03

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Required. Enter a valid email address.', max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('student', 'Student'), ('company', 'Company'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='student', help_text='Determines the user portal and permissions.', max_length=20, verbose_name='user role')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='profile photo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='company logo')),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance & Banking'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('consulting', 'Consulting'), ('media', 'Media & Entertainment'), ('telecom', 'Telecommunications'), ('energy', 'Energy'), ('government', 'Government'), ('nonprofit', 'Non-Profit'), ('other', 'Other')], max_length=50, verbose_name='industry')),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=20, verbose_name='company size')),
                ('description', models.TextField(blank=True, help_text='Brief description of the company', verbose_name='company description')),
                ('website', models.URLField(blank=True, verbose_name='company website')),
                ('address', models.TextField(blank=True, verbose_name='office address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('contact_person', models.CharField(blank=True, help_text='Name of the HR contact person', max_length=255, verbose_name='contact person')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='contact phone')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the company has been verified by administrators', verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, verbose_name='gender')),
                ('address', models.TextField(blank=True, help_text='Current residential address', verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('university', models.CharField(blank=True, help_text='Name of the university or institution', max_length=255, verbose_name='university')),
                ('department', models.CharField(blank=True, help_text='Academic department or faculty', max_length=255, verbose_name='department')),
                ('student_id', models.CharField(blank=True, max_length=50, verbose_name='student ID')),
                ('education_level', models.CharField(blank=True, choices=[('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('diploma', 'Diploma'), ('other', 'Other')], max_length=20, verbose_name='education level')),
                ('current_semester', models.CharField(blank=True, max_length=20, verbose_name='current semester')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='GPA/CGPA')),
                ('expected_graduation', models.DateField(blank=True, null=True, verbose_name='expected graduation')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills (e.g., Python, JavaScript, React)', verbose_name='technical skills')),
                ('experience', models.TextField(blank=True, help_text='Brief description of previous work experience', verbose_name='work experience')),
                ('languages', models.CharField(blank=True, help_text='Languages spoken (e.g., English, Bangla)', max_length=255, verbose_name='languages')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn profile')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub profile')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='portfolio website')),
                ('bio', models.TextField(blank=True, help_text='A short bio about yourself (max 1000 characters)', max_length=1000, verbose_name='biography')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supervisor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('university', models.CharField(blank=True, max_length=255, verbose_name='university')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='department')),
                ('designation', models.CharField(blank=True, choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer'), ('senior_lecturer', 'Senior Lecturer'), ('adjunct', 'Adjunct Faculty'), ('other', 'Other')], max_length=50, verbose_name='designation')),
                ('employee_id', models.CharField(blank=True, max_length=50, verbose_name='employee ID')),
                ('expertise', models.TextField(blank=True, help_text='Comma-separated list of expertise areas', verbose_name='areas of expertise')),
                ('max_students', models.PositiveIntegerField(default=10, help_text='Maximum number of students this supervisor can handle', verbose_name='maximum students')),
                ('bio', models.TextField(blank=True, max_length=1000, verbose_name='biography')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Supervisor Profile',
                'verbose_name_plural': 'Supervisor Profiles',
            },
        ),
    ]
