# Generated by Django 4.2.30 on 2026-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('basic', 'Basic Free ($0/mo)'), ('pro', 'Pro Recruiter ($20/mo)'), ('ultimate', 'Ultimate Enterprise ($80/mo)')], default='basic', max_length=20, verbose_name='subscription plan'),
        ),
    ]
