# Generated by Django 4.2.30 on 2026-09-02 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_status',
            field=models.CharField(choices=[('final_semester', 'Final Semester (Internship Eligible / Only Internship Remaining)'), ('graduated', 'Graduation Completed'), ('continuing', 'Continuing Studies')], default='final_semester', help_text='Indicates whether only the internship semester remains for graduation.', max_length=30, verbose_name='academic status'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_semester',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='current semester'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cumulative Grade Point Average (0.00 - 4.00 scale)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='GPA/CGPA'),
        ),
    ]
