# Generated by Django 4.2.30 on 2026-09-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_academic_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_students', to='accounts.supervisorprofile', verbose_name='academic supervisor'),
        ),
    ]
