# Generated by Django 4.2.30 on 2026-07-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.PositiveIntegerField(help_text='Score from 1 to 10', verbose_name='technical competency')),
                ('communication_score', models.PositiveIntegerField(help_text='Score from 1 to 10', verbose_name='communication skills')),
                ('professionalism_score', models.PositiveIntegerField(help_text='Score from 1 to 10', verbose_name='professionalism')),
                ('attendance_score', models.PositiveIntegerField(help_text='Score from 1 to 10', verbose_name='attendance')),
                ('overall_score', models.PositiveIntegerField(help_text='Score from 1 to 10', verbose_name='overall performance')),
                ('comments', models.TextField(help_text="Detailed feedback on the student's performance", verbose_name='evaluation comments')),
                ('recommendation', models.TextField(blank=True, help_text='Any recommendations for the student', verbose_name='recommendation')),
                ('is_final', models.BooleanField(default=False, verbose_name='final evaluation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internships.internship', verbose_name='internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='accounts.studentprofile', verbose_name='student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='accounts.supervisorprofile', verbose_name='supervisor')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(help_text='Week number of the internship (e.g., 1, 2, 3)', verbose_name='week number')),
                ('title', models.CharField(help_text="Brief title summarizing this week's work", max_length=255, verbose_name='report title')),
                ('activities', models.TextField(help_text='Describe what you accomplished this week', verbose_name='activities completed')),
                ('challenges', models.TextField(blank=True, help_text='Describe any challenges or difficulties encountered', verbose_name='challenges faced')),
                ('next_week_plan', models.TextField(blank=True, help_text='What do you plan to work on next week?', verbose_name='next week plan')),
                ('hours_worked', models.DecimalField(decimal_places=1, default=40, max_digits=5, verbose_name='hours worked')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='status')),
                ('feedback', models.TextField(blank=True, verbose_name='supervisor feedback')),
                ('score', models.PositiveIntegerField(blank=True, help_text='Score out of 100', null=True, verbose_name='score')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='internships.internship', verbose_name='internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='accounts.studentprofile', verbose_name='student')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to='accounts.supervisorprofile', verbose_name='supervisor')),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'verbose_name_plural': 'Weekly Reports',
                'ordering': ['-week_number'],
                'unique_together': {('student', 'internship', 'week_number')},
            },
        ),
    ]
