# Generated by Django 4.2.30 on 2026-07-16 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(help_text='Supported formats: PDF, DOC, DOCX, JPG, PNG', upload_to='documents/', verbose_name='file')),
                ('doc_type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('transcript', 'Academic Transcript'), ('certificate', 'Certificate'), ('portfolio', 'Portfolio'), ('offer_letter', 'Offer Letter'), ('agreement', 'Agreement'), ('evaluation', 'Evaluation Report'), ('report', 'Internship Report'), ('other', 'Other')], default='other', max_length=20, verbose_name='document type')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes', verbose_name='file size')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Registration'), ('profile_update', 'Profile Update'), ('application_submit', 'Application Submitted'), ('interview_schedule', 'Interview Scheduled'), ('report_submit', 'Report Submitted'), ('evaluation_submit', 'Evaluation Submitted'), ('internship_create', 'Internship Created'), ('document_upload', 'Document Uploaded'), ('password_change', 'Password Changed'), ('other', 'Other')], max_length=30, verbose_name='action')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
