# Generated by Django 4.2.30 on 2026-09-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('resume', 'Resume / CV'), ('formal_photo', 'Formal Photo / Picture'), ('certificate', 'Certificate'), ('cover_letter', 'Cover Letter'), ('transcript', 'Academic Transcript'), ('portfolio', 'Portfolio'), ('offer_letter', 'Offer Letter'), ('agreement', 'Agreement'), ('evaluation', 'Evaluation Report'), ('report', 'Internship Report'), ('other', 'Other')], default='other', max_length=20, verbose_name='document type'),
        ),
    ]
