# Generated by Django 4.2.30 on 2026-07-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('technical', 'Technical Interview'), ('hr', 'HR Interview'), ('behavioral', 'Behavioral Interview'), ('group', 'Group Interview'), ('final', 'Final Interview')], default='technical', max_length=20, verbose_name='interview type')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('onsite', 'On-site'), ('phone', 'Phone Call')], default='online', max_length=20, verbose_name='interview mode')),
                ('scheduled_at', models.DateTimeField(verbose_name='scheduled date & time')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='duration (minutes)')),
                ('meeting_link', models.URLField(blank=True, help_text='Video call link (Google Meet, Zoom, etc.)', verbose_name='meeting link')),
                ('location', models.CharField(blank=True, help_text='Address for on-site interviews', max_length=255, verbose_name='location')),
                ('interviewer_name', models.CharField(blank=True, max_length=255, verbose_name='interviewer name')),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20, verbose_name='outcome')),
                ('notes', models.TextField(blank=True, help_text='Notes and feedback from the interview', verbose_name='interview notes')),
                ('score', models.PositiveIntegerField(blank=True, help_text='Score out of 100', null=True, verbose_name='interview score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application', verbose_name='application')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
