# Generated by Django 4.2.30 on 2026-07-16 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application', 'Application Update'), ('interview', 'Interview'), ('report', 'Report'), ('evaluation', 'Evaluation'), ('internship', 'Internship'), ('system', 'System'), ('reminder', 'Reminder'), ('offer', 'Offer')], default='system', max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='priority')),
                ('link', models.CharField(blank=True, help_text='URL to the related page', max_length=500, verbose_name='link')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
